<a href="https://colab.research.google.com/github/aoaguirre123/Proyecto_Mineria_de_datos/blob/main/Clase_24_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 500) # Capability

In [ ]:
df = pd.read_csv('/content/superstore.csv')

In [ ]:
df.head()

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Date,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
0,21865-109365-13542,109365,21865,Xerox 22,Paper,Office Supplies,0.0,2016-11-03,3,11,Thursday,2016,3,Consumer,California,7267,15139
1,15745-162026-16405,162026,15745,Xerox 1925,Paper,Office Supplies,0.0,2016-10-08,8,10,Saturday,2016,2,Consumer,California,21713,48251
2,10090-136448-10461,136448,10090,Logitech 910-002974 M325 Wireless Mouse for We...,Accessories,Technology,0.2,2017-09-16,16,9,Saturday,2017,2,Consumer,Pennsylvania,11210,37368
3,16525-142993-23814,142993,16525,"Contico 72""H Heavy-Duty Storage System",Storage,Office Supplies,0.0,2015-10-12,12,10,Monday,2015,2,Consumer,Washington,0,63826
4,15280-115819-4927,115819,15280,PowerGen Dual USB Car Charger,Phones,Technology,0.2,2016-04-19,19,4,Tuesday,2016,5,Consumer,California,10114,31119

In [ ]:
df.columns

Index(['Transaction ID', 'Order ID', 'Customer ID', 'Product Name',
       'Sub-Category', 'Category', 'Discount', 'Order Date', 'Order Day',
       'Order Month', 'Order Weekday', 'Order Year', 'Quantity', 'Segment',
       'State', 'Profit CLP', 'Sales CLP'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9993 entries, 0 to 9992
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction ID  9993 non-null   object
 1   Order ID        9993 non-null   int64
 2   Customer ID     9993 non-null   int64
 3   Product Name    9993 non-null   object
 4   Sub-Category    9993 non-null   object
 5   Category        9993 non-null   object
 6   Discount        9993 non-null   float64
 7   Order Date      9993 non-null   object
 8   Order Day       9993 non-null   int64
 9   Order Month     9993 non-null   int64
 10  Order Weekday   9993 non-null   object
 11  Order Year      9993 non-null   int64
 12  Quantity        9993 non-null   int64
 13  Segment         9993 non-null   object
 14  State           9993 non-null   object
 15  Profit CLP      9993 non-null   int64
 16  Sales CLP       9993 non-null   int64
dtypes: float64(1), int64(8), object(8)
memory usage: 1.3+ MB

In [ ]:
df['Category'].value_counts()

Category
Office Supplies    6026
Furniture          2120
Technology         1847
Name: count, dtype: int64

In [ ]:
df['Product Name'].value_counts()

Product Name
Staple envelope                         48
Staples                                 46
Easy-staple paper                       46
Avery Non-Stick Binders                 20
Staples in misc. colors                 19
                                        ..
Linden 12" Wall Clock With Oak Frame     1
Plantronics Single Ear Headset           1
4009 Highlighters                        1
Grip Seal Envelopes                      1
Xerox Blank Computer Paper               1
Name: count, Length: 1850, dtype: int64

In [ ]:
df.isnull().sum() # Identificar los valores nulos

Transaction ID    0
Order ID          0
Customer ID       0
Product Name      0
Sub-Category      0
Category          0
Discount          0
Order Date        0
Order Day         0
Order Month       0
Order Weekday     0
Order Year        0
Quantity          0
Segment           0
State             0
Profit CLP        0
Sales CLP         0
dtype: int64

In [ ]:
df.describe().round() # Toma las columas numericas y obtiene estadistica descriptiva de las mismas.

,Order ID,Customer ID,Discount,Order Day,Order Month,Order Year,Quantity,Profit CLP,Sales CLP
count,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000,9993.000000,9.993000e+03,9.993000e+03
mean,134437.893525,16037.562294,0.156188,15.467727,7.810067,2015.722406,3.789753,2.231973e+04,1.789979e+05
std,20252.558140,3429.030030,0.206457,8.748441,3.284598,1.123479,2.225149,1.824389e+05,4.853762e+05
min,100006.000000,10015.000000,0.000000,1.000000,1.000000,2014.000000,1.000000,-5.139733e+06,3.460000e+02
25%,117156.000000,13045.000000,0.000000,8.000000,5.000000,2015.000000,2.000000,1.348000e+03,1.345700e+04
50%,133613.000000,16120.000000,0.200000,15.000000,9.000000,2016.000000,3.000000,6.753000e+03,4.242600e+04
75%,152072.000000,18985.000000,0.200000,23.000000,11.000000,2017.000000,5.000000,2.286700e+04,1.634910e+05
max,169999.000000,21925.000000,0.800000,31.000000,12.000000,2017.000000,14.000000,6.541481e+06,1.762972e+07

In [ ]:
df_limpio = df.dropna() # Elimina valores nulos.

,Transaction ID,Order ID,Customer ID,Product Name,Sub-Category,Category,Discount,Order Date,Order Day,Order Month,Order Weekday,Order Year,Quantity,Segment,State,Profit CLP,Sales CLP
0,21865-109365-13542,109365,21865,Xerox 22,Paper,Office Supplies,0.0,2016-11-03,3,11,Thursday,2016,3,Consumer,California,7267,15139
1,15745-162026-16405,162026,15745,Xerox 1925,Paper,Office Supplies,0.0,2016-10-08,8,10,Saturday,2016,2,Consumer,California,21713,48251
2,10090-136448-10461,136448,10090,Logitech 910-002974 M325 Wireless Mouse for We...,Accessories,Technology,0.2,2017-09-16,16,9,Saturday,2017,2,Consumer,Pennsylvania,11210,37368
3,16525-142993-23814,142993,16525,"Contico 72""H Heavy-Duty Storage System",Storage,Office Supplies,0.0,2015-10-12,12,10,Monday,2015,2,Consumer,Washington,0,63826
4,15280-115819-4927,115819,15280,PowerGen Dual USB Car Charger,Phones,Technology,0.2,2016-04-19,19,4,Tuesday,2016,5,Consumer,California,10114,31119

In [ ]:
df_limpio.to_csv('limpio.csv')